version: '2'

volumes:
  bash-history:

services:
  dev:
    image: eleidan/erlang:22.1.6-ubuntu-16.04
    user: phantom
    volumes:
      - .:/home/phantom/app
      - bash-history:/home/phantom/bash-history
